#con esto puedo agregar campos configuraciones...
version: "3.7"
services:
  backend: #contenedor para el servicio que voy a construir llamado backend
    container_name: backend #nombre de mi contenedor 
    build:
      context: . #para encontrar el archivo
      dockerfile: Dockerfile
    ports: #entramos a puertos
      - 5001:5001
    networks: #aqui tengo mi red
      - processor-net #name
    depends_on:
      minio:
        condition: service_healthy
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    networks:
      - processor-net
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-volume:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root1234
    command: server --console-adress ":9001 /data"
    healthcheck:
        test: ["CMD","curl","-f", "http://localhost:9000/minio/healh/live"]
        interval: 10s
        timeout: 5s
        retries: 5

  networks:
    processor-net:
      driver: bridge

  volumes:
    minio-volume:
      
 
