name: Code workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  code-validation:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/Checkout@v3

      - name: Review files 
        run: ls